Default: &defaults
  database: hgm.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: hgm_test.sqlite3
  <<: *defaults

Staging:
  database: hgm_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: hgm_production.sqlite3
  poolsize: 100
  <<: *defaults
